site_name: Berlin Tour 2017

markdown_extensions:
  - admonition
  - attr_list
  - footnotes

pages:
  - Home: index.md

  - '出発前の準備':
    - '持っていくもの': item-list.md
    - 'スーツケース': suitcase.md
    - '海外対応SIM': sim.md
    - 'ユーロ・通貨': money.md
    - 'モバイルルータ': mobile-router.md

  - '現地情報':
    - 'パリ': paris.md
    - 'アテネ': athens.md
    - 'ベルリン': berlin.md
